name: matrix workflow
on: push

jobs:
  get-matrix-window:
    runs-on: windows-latest
    steps:
      - name: echo
        run: echo hello

  get-matrix-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo hello