name: output workflow
on: push

jobs:
  create-output:
    runs-on: ubuntu-latest
    outputs: # 다른 job에서 output을 사용할 수 있도록 설정
      test: ${{ steps.check-output.outputs.test }}
    steps:
      - name: echo output
        id: check-output
        run: |
          echo "test=hello" >> $GITHUB_OUTPUT
      - name: check output
        run: |
          echo ${{ steps.check-output.outputs.test }}

  get-output:
    needs: [create-output]
    runs-on: ubuntu-latest
    steps:
      - name: get output
        run: echo ${{ needs.create-output.outputs.test }}
