name: environment workflow
on: push

jobs:
  get-env:
    runs-on: ubuntu-latest
    steps:
      - name: check env & secret
        run: |
          echo ${{ var.level }}
          echo ${{ secrets.key }}