name: matrix workflow
on: push

jobs:
  get-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
        version: [ 12, 14 ]
    steps:
      - name: echo
        run: |
          echo $${{ matrix.os }}
          echo $${{ matrix.version }}
